# NumPy
It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices) and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

# Creating Numpy array

In [3]:
import numpy as np

In [4]:
np.__version__

'1.26.4'

In [5]:
import sys
sys.version

'3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 15:03:56) [MSC v.1929 64 bit (AMD64)]'

In [6]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [7]:
type(my_list)

list

In [8]:
np.array([2,4,56,422,32,1]) # 1D Array

array([  2,   4,  56, 422,  32,   1])

In [9]:
a = np.array([2,4,56,422,32,1]) # Vector
print(a)

[  2   4  56 422  32   1]


In [10]:
type(a)

numpy.ndarray

In [11]:
# 2D Array (Matrix)
new = np.array([[45,34,22,2],[24,55,3,22]])
print(new)

[[45 34 22  2]
 [24 55  3 22]]


In [12]:
# 3D  (Tensor)
np.array([[2,3,33,4,45],[23,45,56,66,2],[357,523,32,24,2],[32,32,44,33,234]])

array([[  2,   3,  33,   4,  45],
       [ 23,  45,  56,  66,   2],
       [357, 523,  32,  24,   2],
       [ 32,  32,  44,  33, 234]])

# dtype

The desired datatype for the array. If not given, then the type will be determined as the minimum type required to hold the objects in the sequence.

In [15]:
np.array([11,23,44],dtype = float)

array([11., 23., 44.])

In [16]:
np.array([11,23,44],dtype = bool) # Here its True becoz, python treats Non-Zero

array([ True,  True,  True])

In [17]:
np.array([1,2,0],dtype = bool)

array([ True,  True, False])

In [18]:
np.array([24,55,89],dtype = complex)

array([24.+0.j, 55.+0.j, 89.+0.j])

# arange

arange can be called with a varying number of positional arguments.

In [20]:
np.arange(15) #displays from 0 to 14, excluding 15

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
np.arange(3.7)

array([0., 1., 2., 3.])

In [22]:
np.arange(1,25) #includes 1 , excludes the last numbr 25

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [23]:
np.arange(1,25,4) #strides -> Alternate numbers

array([ 1,  5,  9, 13, 17, 21])

In [24]:
ar = np.arange(-30,20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

# reshape
Both of the number products should be equal to number of items present inside the array.

In [26]:
np.arange(2,16).reshape(2,7) #converted into 2 rows and 7 columns

array([[ 2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15]])

In [27]:
np.arange(1,9).reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# ones and zeros
You can initialise the values and create values.

In [29]:
np.ones((2,4)) #we have to mention inside the tuple

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [30]:
np.ones(6) #parameter tuning

array([1., 1., 1., 1., 1., 1.])

In [31]:
np.ones((3,4),dtype = int) #hyper parameter tunning

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [32]:
np.zeros(5) #parameter tuning

array([0., 0., 0., 0., 0.])

In [33]:
np.zeros((4,5),dtype = int) #hyper parameter tuning

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

# Creating an empty array with 2 elements
The function empty creates an array whose initial content is random and depends on the state of the memory.

In [35]:
np.empty(2)

array([ 2.88292265e+222, -9.25513009e-068])

In [36]:
# another type ----- random()
np.random.random(4)

array([0.64304513, 0.45554365, 0.84790175, 0.55450357])

In [37]:
np.random.rand(6)

array([0.54614804, 0.40880174, 0.18901113, 0.45494704, 0.05454388,
       0.89476722])

In [38]:
np.random.rand(3,5,2)

array([[[0.74217154, 0.49742751],
        [0.23025652, 0.94427134],
        [0.9866435 , 0.19862822],
        [0.95283396, 0.20883928],
        [0.22465607, 0.46604815]],

       [[0.45675954, 0.94215974],
        [0.19297797, 0.2660364 ],
        [0.41289973, 0.58025075],
        [0.18070855, 0.25298506],
        [0.26889199, 0.56868552]],

       [[0.93987545, 0.4813488 ],
        [0.68127547, 0.1747263 ],
        [0.76805832, 0.95498486],
        [0.62370531, 0.2970613 ],
        [0.82575268, 0.79361885]]])

In [39]:
np.random.randint(3,5) #includes 3 or 4 and exludes 5

4

In [40]:
np.random.randint(3,5) #includes 3 or 4 and exludes 5

3

In [41]:
np.random.rand(0,10,3)

array([], shape=(0, 10, 3), dtype=float64)

# linspace
It is also called as Linearly space, linearly separable, in a given range at equal distance it creates points.

In [43]:
np.linspace(-10,12,2) #here parameters are lower range, upper range, number of items to generate

array([-10.,  12.])

In [44]:
np.linspace(4,16,6)

array([ 4. ,  6.4,  8.8, 11.2, 13.6, 16. ])

In [45]:
np.linspace(0,12,num = 6)

array([ 0. ,  2.4,  4.8,  7.2,  9.6, 12. ])

# identity
identity matrix is that diagonal items will be ones and everything will be zeros

In [47]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Array attributes

In [49]:
a1 = np.arange(10) #1D
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
a2 = np.arange(12,dtype = float).reshape(2,6) #Matrix
a2

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.]])

In [51]:
a3 = np.arange(8).reshape(2,2,2) #3D - Tensor
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

# ndim
To findout given array number of dimensions

In [53]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
a1.ndim #a1 is 1D

1

In [55]:
a2


array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.]])

In [56]:
a2.ndim #a2 is 2D

2

In [57]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [58]:
a3.ndim #a3 is 3D

3

# shape
gives each item which consist of number of rows and number of columns

In [60]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
a1.shape

(10,)

In [62]:
a2

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.]])

In [63]:
a2.shape

(2, 6)

In [64]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [65]:
a3.shape

(2, 2, 2)

# size
gives the number of items

In [67]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [68]:
a3.size

8

In [69]:
a2

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.]])

In [70]:
a2.size

12

# item size
Memory occupied by the item

In [72]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
a1.itemsize #bytes

4

In [74]:
a2

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.]])

In [75]:
a2.itemsize #float 64 gives 8bytes

8

In [76]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [77]:
a3.itemsize #integer 32 gives 4 bytes

4

# dtype
gives data type of the item

In [79]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


# Changing data type

In [81]:
#astype

x = np.array([33,22,2.5])
x

array([33. , 22. ,  2.5])

In [82]:
x.astype(int)

array([33, 22,  2])

# Array operations

In [84]:
z1 = np.arange(12).reshape(3,4)
z2 = np.arange(12,24).reshape(3,4)

In [85]:
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [86]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# scalar operations

Scalar operations on Numpy array include performing addition or subtraction or multiplication on each element of a Numpy array.

In [88]:
#arithmetic
z1 + 2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [89]:
#subtraction
z1 - 2

array([[-2, -1,  0,  1],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9]])

In [90]:
#Multiplication
z1 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [91]:
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [92]:
#power
z1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [93]:
#Modulo
z1 % 2 #if divisible by 2 gives remainder 0, then it gives output as 0, otherwise gives 1

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]], dtype=int32)

# Relational Operators
The relational operators are also called as comparision operators, their main function is to return either a true or false based on the value of operands.

In [95]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [96]:
z2 > 2

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [97]:
z2 > 20

array([[False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True]])

# Vector Operation
We can apply on both numpy arrays

In [99]:
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [100]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [101]:
#Arithmetic
z1 + z2 #both numpy array Shape is same and we can add item wise

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [102]:
z1 * z2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [103]:
z1 - z2

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

In [104]:
z1 / z2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

# Array Functions

In [106]:
k1 = np.random.random((3,3))
k1 = np.round(k1*100)
k1

array([[94.,  3., 68.],
       [26., 92.,  3.],
       [54., 63., 92.]])

In [107]:
#Max
np.max(k1)

94.0

In [108]:
#min
np.min(k1)

3.0

In [109]:
#sum
np.sum(k1)

495.0

In [110]:
#product
np.prod(k1)

43068781776384.0

In Numpy 0 represents column, 1 is row

In [112]:
k1

array([[94.,  3., 68.],
       [26., 92.,  3.],
       [54., 63., 92.]])

In [113]:
# if we want the maximum of every row
np.max(k1, axis = 1)

array([94., 92., 92.])

In [114]:
# if we want the maximum of every column
np.max(k1, axis = 0)

array([94., 92., 92.])

In [115]:
#product of every column
np.prod(k1, axis = 0)

array([131976.,  17388.,  18768.])

In [116]:
k1.min(axis = 0)

array([26.,  3.,  3.])

# Statistics related functions

In [118]:
k1

array([[94.,  3., 68.],
       [26., 92.,  3.],
       [54., 63., 92.]])

In [119]:
# mean
k1.mean(axis = 0)

array([58.        , 52.66666667, 54.33333333])

In [120]:
#median
np.median(k1)

63.0

In [121]:
#Standard deviation
np.std(k1)

34.54787338687514

In [122]:
np.std(k1, axis = 0)

array([27.90459938, 37.06151043, 37.59728123])

In [123]:
#Variance
np.var(k1)

1193.5555555555557

# Trigonometry functions

In [125]:
np.sin(k1)

array([[-0.24525199,  0.14112001, -0.89792768],
       [ 0.76255845, -0.77946607,  0.14112001],
       [-0.55878905,  0.1673557 , -0.77946607]])

In [126]:
np.cos(k1)

array([[ 0.96945937, -0.9899925 ,  0.44014302],
       [ 0.64691932, -0.62644445, -0.9899925 ],
       [-0.82930983,  0.98589658, -0.62644445]])

In [127]:
np.tan(k1)

array([[-0.2529781 , -0.14254654, -2.0400816 ],
       [ 1.17875355,  1.24427006, -0.14254654],
       [ 0.6738001 ,  0.16974975,  1.24427006]])

# dot product
The numpy module of Python provides a function to perform the dot product of two arrays.

In [129]:
s2 = np.arange(12).reshape(3,4)
s3 = np.arange(12,24).reshape(4,3)

In [130]:
s2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [131]:
s3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [132]:
np.dot(s2,s3) #dot product of s2, s3

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

# Log and exponents

In [134]:
np.exp(s2)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

__round/floor/ceil__

1. __round__
   The numpy.round() function rounds the elements of an array to the nearest integer or to the specified number of decimals.

In [136]:
#Round to the nearest integer
arr = np.array([1.2,2.7,3.5,4.9])
rounded_arr = np.round(arr)
print(rounded_arr)

[1. 3. 4. 5.]


In [137]:
#Round to two decimals 
arr = np.array([1.234, 2.567, 3.891]) 
rounded_arr = np.round(arr, decimals=2) 
print(rounded_arr) 

[1.23 2.57 3.89]


In [138]:
#randomly
np.round(np.random.random((2,3)) * 100)

array([[ 6.,  7., 54.],
       [71., 73., 85.]])

__2.floor__

The numpy.floor() function returns the largest integer less than or equal to each element of an array.

In [140]:
# Floor operation 
arr = np.array([1.2, 2.7, 3.5, 4.9])
floored_arr = np.floor(arr)
print(floored_arr)

[1. 2. 3. 4.]


In [141]:
np.floor(np.random.random((2,3)) * 100) 

array([[71.,  1., 46.],
       [22., 57., 62.]])

__3.Ceil__

The numpy.ceil() function returns the smallest integer greater than or equal to each element of an array.

In [143]:
arr = np.array([1.2, 2.7, 3.5, 4.9])
ceiled_arr = np.ceil(arr)
print(ceiled_arr)

[2. 3. 4. 5.]


In [144]:
np.ceil(np.random.random((2,3)) * 100) 

array([[72., 97., 86.],
       [65., 18., 45.]])

# __Indexing and Slicing__

In [146]:
p1 = np.arange(10)
p2 = np.arange(12).reshape(3,4)
p3 = np.arange(8).reshape(2,2,2)

In [147]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [148]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [149]:
p3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

# Indexing on 1D array

In [151]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [152]:
#fetching the last item
p1[-1]

9

In [153]:
#fetching the first item
p1[0]

0

# Indexing on 2D array

In [155]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [156]:
# fetching the desired element : 6
p2[1,2]

6

In [157]:
# fetching the desired element : 11
p2[2,3]

11

In [158]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [159]:
#fetching the desired element : 4
p2[1,0]

4

# Indexing on 3D (Tensors)

In [161]:
p3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [162]:
# fetching desired element : 5
p3[1,0,1]

5

In [163]:
#fetching desired element : 2
p3[0,1,0]

2

In [164]:
#fetching desired element : 0
p3[0,0,0]

0

In [165]:
#fetching desired element : 6
p3[1,1,0]

6

# Slicing
Fetching multiple items

# Slicing on 1D

In [167]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [168]:
#fetching desired elements are : 2,3,4
p1[2:5]

array([2, 3, 4])

In [169]:
# Alternate (same as python)
p1[2:5:2]

array([2, 4])

In [170]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [171]:
#fetching total first row
p2[0, :] #Here 0 represents the first row and (:) represents Total column

array([0, 1, 2, 3])

In [172]:
#fetching total third column
p2[:, 2]

array([ 2,  6, 10])

In [173]:
#fetch 5,6 and 9,10
p2[1:3] #for rows

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [174]:
p2[1:3,1:3] #for columns

array([[ 5,  6],
       [ 9, 10]])

In [175]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [176]:
#fetch 0,3 and 8,11
p2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [177]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [178]:
p2[::2,2:4]

array([[ 2,  3],
       [10, 11]])

# Slicing in 3D

In [183]:
p3 = np.arange(27).reshape(3,3,3)
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [185]:
#fetch second matrix
p3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [187]:
#fetch first and last matrix
p3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [189]:
#fetch 1 2s array's 2 row - 3,4,5
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [197]:
p3[0]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [199]:
p3[0,1,:]

array([3, 4, 5])

In [201]:
#Fetch 2 numpy array, middle column -- 10,13,16
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [209]:
p3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [211]:
p3[1,:,1]

array([10, 13, 16])

In [213]:
p3[2] #last row

array([[18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

In [245]:
p3[2,1:] #last 2 rows

array([[21, 22, 23],
       [24, 25, 26]])

In [247]:
#last 2 columns
p3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [249]:
#Fetch 0,2,18,20
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [257]:
p3[0::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [261]:
p3[0::2, 0 , ::2] #for columns

array([[ 0,  2],
       [18, 20]])